name: flutter_todos
description: A Todo-List-App.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  cloud_firestore: ^1.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.9.2
  equatable: ^2.0.0
  firebase_core: ^1.0.2
  flutter_bloc: ^7.0.0
  get_it: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3

flutter:
  uses-material-design: true
  assets:
    - lang/en.json
    - lang/de.json
